### ISSUE TITLE
Support for samples from different lineages?

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#19]
It doesn't seem like this code is able to handle samples from different lineages:

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L79-L84

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L111

It looks like it is assumed that all samples have the same lineage assignment, which is not always the case.

**Comment by nhhaidee** [comment]
Fixed by https://github.com/nhhaidee/scovtree/pull/17/commits/fa18e8ed8f4538c5719a907ddce00c8f6a4fb3d7

**Comment by peterk87** [comment]
Hi @nhhaidee 

In the future if possible, can you address each issue in a separate PR? It would make it much easier to track what changes address what issues.

---

For changes to `bin/filter_gisaid_sequences.py` in fa18e8e:

1. Can you update your tests? Maybe add a sequence from a different lineage to your test dataset input sequences file?
2. How does GISAID sequence filtering and tree pruning work with samples from multiple lineages? Are GISAID sequences from each lineage sampled equally up to a certain limit?
3. Why are both `sample_lineage` and `lineage_report` required options yet have default values of `""` (empty string)? Doesn't that mean that they are optional parameters? What if both are set to `None`/`""`?

It looks like `bin/prune_down_tree.py` needs to be updated since it looks like it is assumed that all user input samples are related and belong to the same lineage:

https://github.com/nhhaidee/scovtree/blob/fa18e8ed8f4538c5719a907ddce00c8f6a4fb3d7/bin/prune_down_tree.py#L26

It also looks like user sequences could be pruned out of the final tree.

---

The `drop_duplicates` is typically used to get rid of duplicate entries in a Pandas DataFrame and `pd.read_csv` should be used with a CSV file instead of `pd.read_table` with `sep='\t'`:

https://github.com/nhhaidee/scovtree/blob/fa18e8ed8f4538c5719a907ddce00c8f6a4fb3d7/bin/filter_gisaid_sequences.py#L78-L84


If you want the unique lineages you can either use the Pandas Series method `unique` or convert the Series to a Python set:


```python
df_lineage_report = pd.read_csv(lineage_report)
lineages = set(df_lineage_report['lineage']) - set('None')
```

- `"None"` is sometimes returned as the Pangolin lineage assignment when sequence quality is poor (too many Ns; sequence too short), so it may be a good idea to filter that value out just in case.

**Comment by nhhaidee** [comment]
@peterk87 I updated the test with multiple lineages, the workflow is fine with small of numbers of taxa (< 100) because we don't need to filter and prune tree.
And yes, the prune tree down step has to be updated to handle multiple lineages., I have found the issue with that

**Comment by nhhaidee** [comment]
@peterk87 What do you think when multiple lineages presented in the different part (different sub tree) in phylogenetic tree? For example, samples with lineage B.1.618 and B.1.1.7 will be in the different subtrees. The tree will be large when we visualise them together with shiptv. 
Is it ok, if we visualise separate tree for each lineage?

**Comment by nhhaidee** [comment]
[shiptv_phylogenetic_tree.zip](https://github.com/nhhaidee/scovtree/files/6673443/shiptv_phylogenetic_tree.zip)
Here is the result for small tree for you reference.

**Comment by nhhaidee** [comment]
How do you think if we do sampling with equally probabilities as below:
`df_sample= df.groupby('Pango_lineage').apply(lambda x: x.sample(int((len(x)/len(df))*total_sample_size)))` where `total_sample_size=10000`

IQTree will always run with manageable number of sequences, then prune tree and get leaflist for lineage

**Comment by peterk87** [comment]
I don't think that will work since it would be dropping small lineages, e.g.

```python
# 10 samples in lineage
# around 500k samples belonging to all lineages filtered for
# only getting up to 10k total samples
int((10/500000)*10000)
# => 0
# no samples retrieved for this small lineage
```

I think it would be more appropriate to be biased towards including samples from the low abundance lineages before the larger lineages. 

> Is it ok, if we visualise separate tree for each lineage?

That would be a good output as well as well as showing all user sequences in the same tree.

**Comment by nhhaidee** [comment]
Could you suggest quantity to determine low abundance lineages? I am thinking < 10% of total number of samples is considered as low abundance

I updated code to get all leaflist for user sequences so shiptv can visualize different subtrees together
https://github.com/nhhaidee/scovtree/blob/f45df37b278241cf110b06b0abf5bb77e3f15493/bin/prune_down_tree.py#L28-L38

**Comment by peterk87** [comment]
It looks like the first taxa in the list will be preferentially added to the `clade_neighbors` set. Also the user's sequences may be excluded if `clade_neighbors` is filled up. 

It may be better if neighboring taxa could be added [in a kind of round-robin style](https://en.wikipedia.org/wiki/Round-robin_scheduling) one at a time until the max taxa to show is reached. I think this would require computing the distance of each user sequence taxon to neighboring taxa up to `max_taxa` (similar code to above to generate distances; see [Phylo Tree/Clade `distance` method](https://github.com/biopython/biopython/blob/cd51f64803eba6b1fdef1a7e9cdb70fdf89cafa2/Bio/Phylo/BaseTree.py#L493) (looks very slow so you probably want to limit how many distances are calculated as much as possible)). Iteration through all user taxa adding nearest neighboring taxon until number of taxa equals `max_taxa`.

---

FYI I am testing the workflow with my own data to see if it does what I expect it to. I'm also working on a PR with some changes I'd like you to review.

**Comment by nhhaidee** [comment]
Test cases:
Sample Lineages in GISAID  B.1.2 (> 100,000 sequences); B.1.617.2 ( > 37,000 sequences); B.1.618 ( > 180 sequences)
Input sequences: B.1.2 has 2 sequences, B.1.617.2 has 1 sequence, B.1.618 has 1 sequence

Test Case 1: 2 input consensus sequences belong to B.1.2 lineage (Passed)
Test Case 2: 1 input consensus sequence belong to B.1.617.2 lineage (No Run)
Test Case 3: 1 input consensus sequence belong to B.1.618 lineage (Passed)
Test Case 4: Mix consensus sequences (B.1.2 + B.1.617.2) (No Run)
Test Case 5: Mix consensus sequences (B.1.2 + B.1.618) (No Run)
Test Case 6: Mix consensus sequences (B.1.617.2 + B.1.618) (Failed)
Test Case 7: Mix consensus sequences (B.1.2 + B.1.617.2 + B.1.618) (Passed)
Test Case 8: test_gisaid, test_gisaid_custom (Passed)

Test Case 6 Failed with SHIPTV Process with error `RecursionError: maximum recursion depth exceeded while calling a Python object`. Please see log file 
[comman_shiptv.log](https://github.com/nhhaidee/scovtree/files/6719351/comman_shiptv.log)

I will double check test case 6 again.
