### ISSUE TITLE
Update nextflow_schema.json

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#2]
The help message is not very helpful currently as a lot of the default values are missing for many of the parameters.

- add default values for params
- `reference_fasta` should point to URL of MN908947.3 FASTA (e.g. https://github.com/peterk87/nf-test-datasets/raw/master/genome/MN908947.3/MN908947.3.fa)

The nf-core workflow parameter editor is very useful and handy for editing a `nextflow_schema.json`:

https://nf-co.re/pipeline_schema_builder

**Comment by nhhaidee** [comment]
Work in progress (https://github.com/nhhaidee/scovtree/pull/11)

**Comment by nhhaidee** [comment]
Updated by https://github.com/nhhaidee/scovtree/pull/16

**Comment by nhhaidee** [comment]
Fixed by PR https://github.com/nhhaidee/scovtree/pull/30
