### ISSUE TITLE
Reduce code duplication for selecting metadata in bin/filter_gisaid_sequences.py

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#20]
There is a lot of repetition and code duplication in this code:

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L110-L123

It can be rewritten as

```python
# lineages is a set of lineage strings
mask = df_gisaid_metadata['Pango_lineage'].isin(lineages)
if country:
    mask = mask & df_gisaid_metadata['Location'].str.contains(country)
if region:
    mask = mask & df_gisaid_metadata['Location'].str.contains(region)
df_subset = df_gisaid_metadata.loc[mask, :]
```

**Comment by nhhaidee** [comment]
Fixed by https://github.com/nhhaidee/scovtree/pull/17/commits/fa18e8ed8f4538c5719a907ddce00c8f6a4fb3d7
