### ISSUE TITLE
bin/filter_gisaid_sequences.py: redundant and non-idiomatic Python code

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#21]
Why is this `strains_of_interest_dict` created when you already have a set with the strain names you're interested in?

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L126-L131

Also this kind of check is neither necessary nor idiomatic Python:

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L130-L131

It should simply be 

```python
strains_of_interest_dict[vname] = vname
```

But there's no reason why this dict should exist where the key and value are the same - you can just use a set, which already exists.

And this check should just use the `strains_of_interest` set:

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L149

which is commented out for some reason?

The check for presence of a key in a dict or an item in a set in Python is simply:

```python
if item in set:
# or
if key in dict:
```

**Comment by nhhaidee** [comment]
I changed code to use hash table to check whether strains is in `strains_of_interest`. Code `if strains not in strains_of_interest` may take O(n), by using dict the average time complexity is O(1) that is the reason why I created `strains_of_interest_dict = {}`

**Comment by nhhaidee** [comment]
I just checked the data structure used in set is Hashing and the time complexity of "check if item in set" takes O(1) in average. So the code is unnecessary and will be removed.
https://www.geeksforgeeks.org/internal-working-of-set-in-python/
