### ISSUE TITLE
Logging configuration should be set before any work is done by a script

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#22]
Any logging configuration should be happening soon after the script enters its main function not after all the work has already been done. 

For example, what's the point of this when the script is already nearly finished running?

https://github.com/nhhaidee/scovtree/blob/d9295d05a0f64d08af35d292dac7e50e2ad4ef92/bin/filter_gisaid_sequences.py#L207-L212

You're not getting any the benefits of logging or Rich tracebacks.

Here's how it should look so that if any exceptions are encountered then the tracebacks will be full of useful information:

```python
from rich.logging import RichHandler
...
def main(...):
    """<docstring>"""
    from rich.traceback import install

    install(show_locals=True)

    logging.basicConfig(
        format="%(message)s",
        datefmt="[%Y-%m-%d %X]",
        level=logging.INFO if not verbose else logging.DEBUG,
        handlers=[RichHandler(rich_tracebacks=True, tracebacks_show_locals=True)],
    )
    # do stuff
```

Note that the logging configuration is done *before* anything else.

**Comment by nhhaidee** [comment]
Fixed by PR https://github.com/nhhaidee/scovtree/pull/30
