### ISSUE TITLE
There shouldn't be a default value for the "sample_lineage" workflow parameter; is this parameter necessary?

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#23]
There should be no default set for the `sample_lineage`:

https://github.com/nhhaidee/scovtree/blob/fa18e8ed8f4538c5719a907ddce00c8f6a4fb3d7/nextflow_schema.json#L87-L93

I don't know if this should be a workflow parameter if Pangolin run on user input sequences to determine the lineages those samples belong to. There might be a use case where a user might want to show some GISAID sequences from a particular lineage in the tree along with sequences from the lineages  the user's sequences belong to.

**Comment by nhhaidee** [comment]
At the beginning, I was thinking that filter_gisaid_sequences.py can be used in the case that user can specific lineage, country, region for filtering so `sample_lineage` is a parameter of script. For now, with this workflow it is unnecessary and it will be removed.

**Comment by nhhaidee** [comment]
Fixed by PR https://github.com/nhhaidee/scovtree/pull/30
