### ISSUE TITLE
Simplify workflow

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#3]
Are subworkflows for this workflow necessary?

A subworkflow for every process is overkill making it harder to figure out what the workflow is supposed to do from reading the code. It makes more sense to put at least 2 processes into a subworkflow. To be honest, I don't really see the need for subworkflows for this workflow since there aren't that many steps in this workflow.

**Comment by nhhaidee** [comment]
Work in progress (https://github.com/nhhaidee/scovtree/pull/11)

**Comment by nhhaidee** [comment]
This enhancement was addressed by https://github.com/nhhaidee/scovtree/pull/17/commits/d9295d05a0f64d08af35d292dac7e50e2ad4ef92
