### ISSUE TITLE
Input sequence IDs may be mangled by Pangolin

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#39]
Pangolin tends to mangle the sequence ID for input FASTA sequences.

For example, this FASTA header

```
>MW422255.1 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/USA/SEARCH-5574-SAN/2020, complete genome
```

Turns into this

```
MW422255.1_Severe_acute_respiratory_syndrome_coronavirus_2_isolate_SARS-CoV-2/human/USA/SEARCH-5574-SAN/2020__complete_genome
```

Other programs like IQ-TREE correctly only pull out the ID (i.e. `MW422255.1` for example above) like BioPython does when using `SeqIO`.

It may be necessary to prepare input FASTA sequences for Pangolin analysis so that the results can be easily linked to the original sequences and tree taxa.

**Comment by nhhaidee** [comment]
@peterk87 So you mean that we may need process to correct IDs of input sequences before pangolin analysis?

**Comment by peterk87** [comment]
@nhhaidee one option is to "prepare" the user input sequences for Pangolin analysis by stripping away anything after the first whitespace character

e.g. change
```
>MW422255.1 Severe acute respiratory syndrome coronavirus 2 isolate SARS-CoV-2/human/USA/SEARCH-5574-SAN/2020, complete genome
```
to 
```
>MW422255.1
```

**Comment by nhhaidee** [comment]
OK. Another option is to strip away anything after the first `|` character like in fasta file of  gisiad

`hCoV-19/Australia/NT12/2020|2020-03-25|2020-04-17`

**Comment by peterk87** [comment]
Sure, you can trim away the text after the first pipe character or whitespace character. However, if a `|` is found, then whitespace should probably be replaced with `_` since it's probably a GISAID input sequence. 

FYI the pipe delimiter that GISAID uses is unique to GISAID. NCBI (and pretty much everyone else in the world) uses `>{id} {description}` format for FASTA headers. BioPython expects this format when parsing FASTA files.

**Comment by nhhaidee** [comment]
@peterk87 Please let me know your comments about below cases:
```python
def correctID(strain: str) -> str:
    if '|' in strain: # GISAID sequence "hCoV-19/England/NOTT-10E5C6/2020|2020-03-23|2020-04-14 description", remove anything after first `|`
        strain = re.sub(r'\|.*$', "", strain) 
    else: #NCBI format >{id} {description}, remove anything after first white space
        strain = re.sub(r'\s.*$', "", strain)
    return strain
```

**Comment by peterk87** [comment]
@nhhaidee  

- pull those comments into a docstring explaining what the function is trying to do
-  try to avoid inline comments as much as possible please (see https://www.python.org/dev/peps/pep-0008/#inline-comments)
- `correctID` -> `get_seq_id`; please follow Python naming conventions (see https://www.python.org/dev/peps/pep-0008/#naming-conventions)
- `strain` -> `header`

**Comment by nhhaidee** [comment]
OK @peterk87 I just put comment here for easy understanding, it will be removed in official code. I will add a process to correct sequences ID before pangolin analysis.
