### ISSUE TITLE
Do not modify the GISAID collection date for shiptv visualization

### ISSUE THREAD

**Issue by peterk87** [nhhaidee/scovtree#7]
Leave the collection date unmodified for shiptv visualization so that it can be visualized with a linear quantitative colour palette. Replacing 2020-11 with 2020-11-XX causes the dates to be treated as categorical data so it won't apparent visually what sequences were collected more recently than others.

**Comment by nhhaidee** [comment]
@peterk87 Fixed https://github.com/nhhaidee/scovtree/commit/ef53b4d522429002866e5b001673e2eb23c3f65c
